name: Build Kmod KMM images

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Load build matrix
        id: set-matrix
        run: |
          echo "matrix=$(cat build-matrix.json | tr -d '\n')" >> $GITHUB_OUTPUT

  build:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install container tools
        run: |
          sudo apt-get update
          sudo apt-get install -y podman buildah
      
      - name: Build images for driver ${{ matrix.driver }}
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          echo "Building for driver: ${{ matrix.driver }}"
          echo "OCP versions: ${{ join(matrix.ocp_versions, ', ') }}"
          # TODO: Add actual build steps here