name: Shellcheck

on:
  pull_request:
    paths:
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Third-party tool: ShellCheck via ludeeus/action-shellcheck
      # Used for shell script syntax validation and best practices
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master